services:
  github-runner:
    image: myoung34/github-runner:debian-bookworm
    environment:
      - RUNNER_SCOPE=org
      - ORG_NAME=${ORG_NAME}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - EPHEMERAL=true
      - ACTIONS_RESULTS_URL=${ACTIONS_RESULTS_URL}
      - LABELS=${LABELS}
    entrypoint: ["/patched-entrypoint.sh"]
    command: ["./bin/Runner.Listener", "run", "--startuptype", "service"]
    configs:
      - source: patched_entrypoint_config
        target: /patched-entrypoint.sh
        mode: 0555

configs:
  patched_entrypoint_config:
    name: patched-entrypoint-script
    content: |
      #!/usr/bin/env bash

      set -eo pipefail

      # PATCH Runner.Worker.dll
      sed -i 's/\x41\x00\x43\x00\x54\x00\x49\x00\x4F\x00\x4E\x00\x53\x00\x5F\x00\x52\x00\x45\x00\x53\x00\x55\x00\x4C\x00\x54\x00\x53\x00\x5F\x00\x55\x00\x52\x00\x4C\x00/\x41\x00\x43\x00\x54\x00\x49\x00\x4F\x00\x4E\x00\x53\x00\x5F\x00\x52\x00\x45\x00\x53\x00\x55\x00\x4C\x00\x54\x00\x53\x00\x5F\x00\x4F\x00\x52\x00\x4C\x00/g' /actions-runner/bin/Runner.Worker.dll

      exec /entrypoint.sh "$@"
